### ISSUE TITLE
Add to calendar link doesn't work.

### ISSUE THREAD

**Issue by berhalak** [learnwithjason/learnwithjason.dev#48]
Add to calendar link doesn't work from the home page https://www.learnwithjason.dev/calendar

**Comment by jlengstorf** [comment]
@berhalak hi!

Can you say more about what's not working?

It should open Google Calendar and add the Learn With Jason calendar at the left-hand side under "My Calendars".

<img width="931" alt="Screen Shot 2022-03-11 at 5 07 48 PM" src="https://user-images.githubusercontent.com/163561/157997360-41a041bb-6758-4bca-b7f5-c581ce3d2e7d.png">

Are you seeing an error? Something different?

**Comment by berhalak** [comment]
Hi, sorry I thought that this is a general problem :).

I see this error page (Chrome, Ubuntu)
Application Error
TypeError: Failed to fetch
    at qe (https://www.learnwithjason.dev/build/_shared/chunk-2YF75G26.js:9:3089)
    at Object.loader (https://www.learnwithjason.dev/build/_shared/chunk-2YF75G26.js:9:15972)
    at Je (https://www.learnwithjason.dev/build/_shared/chunk-2YF75G26.js:9:12708)
    at https://www.learnwithjason.dev/build/_shared/chunk-2YF75G26.js:9:12581
    at Array.map (<anonymous>)
    at Pt (https://www.learnwithjason.dev/build/_shared/chunk-2YF75G26.js:9:12574)
    at f (https://www.learnwithjason.dev/build/_shared/chunk-2YF75G26.js:9:11448)
    at $ (https://www.learnwithjason.dev/build/_shared/chunk-2YF75G26.js:9:10395)
    at Object.b [as send] (https://www.learnwithjason.dev/build/_shared/chunk-2YF75G26.js:9:5393)
    at https://www.learnwithjason.dev/build/_shared/chunk-2YF75G26.js:9:17582

**Comment by jlengstorf** [comment]
ah, I see what you mean! I was using the Remix `Link` component and that was skipping my redirect for `/calendar` — it should be fixed now! Thanks!
